version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tjan-mcsr
    restart: unless-stopped
    environment:
      - BOT_NAME
      - OAUTH_TOKEN

